# [build]
# command = "NODE_OPTIONS=--max-old-space-size=4096 bun run build"
# publish = "dist/client"

# [dev]
# command = "bun run dev"

# [[plugins]]
# package = "/plugins/crawler"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
  command = "bun run build"
  publish = "dist/client"

[build.environment]
  BUN_VERSION = "1.3.9"